### ISSUE TITLE
Remoting nodes

### ISSUE THREAD

**Issue by ppotok** [marvinroger/homie#13]
Hello, first: Thank you for great work! you make my develop a lot easier!

Please can you point me out, how to remote for example LED strip?
I didn't find any topic where I should publish values.

Also do you have any toggle button example just for sending status of button? I looked into itead sonoff button, but I am not wise from it :-(

Thank you very much!

**Comment by peter-clarke** [comment]
I was also scratching my head a little at one point earlier this afternoon.

Using the LightOnOff example you would use the following topic:
homie/**DEVICEID**/light/on/set
Simply set the payload on the topic above to "true" for on and "false" for off.

**Comment by ppotok** [comment]
yop, I figured out this too, but how to remote LED strip?

**Comment by peter-clarke** [comment]
I dont have anything to test with but it might be
homie/DEVICEID/led/color/set
The payload would then be an RGB value i.e. 0,255,255

This may be of some help to you.
[http://www.instructables.com/id/ESP8266-Led-Strip-MQTT-Control-Lights-WS2812/](url)

**Comment by euphi** [comment]
You can find an example for an RGB LED-Strip plus White LED-Strip here (for Homie-2.0):

https://github.com/euphi/HomieNodeCollection/blob/master/src/RGBWNode.h
https://github.com/euphi/HomieNodeCollection/blob/master/src/RGBWNode.cpp

This implementation uses
```
ROOT/DEVICEID/LED/r/set
ROOT/DEVICEID/LED/g/set
ROOT/DEVICEID/LED/b/set
ROOT/DEVICEID/LED/w/set
```
as Topics to set.

To compile it, you need the other files in the directory, too. Or you can remove references to my LoggerNode class and (its LN instance) and to the display integration (references to OLEDFrame and OLEDOverlay classes).

**Comment by 466** [comment]
I am having trouble getting this working too... .

Using https://github.com/marvinroger/homie-esp8266/blob/develop/examples/LightOnOff/LightOnOff.ino
and the UI bundle, i connected the device to my network and my mqtt broker.

The devices publishes it's infos to the broker, e.g. using wildcard subscription:

> $ mosquitto_sub -h localhost -t "#"
> 2.0.0
> esp8266
> 18:FE:34:E8:15:5D
> switch
> on:settable
> friendlyname
> 192.168.178.23
> 60
> awesome-relay
> 1.0.0
> 2629e08be5c308f34c1a678c88f0ac6d
> {"wifi":{"ssid":"MyWifi"},"mqtt":{"host":"192.168.178.83","port":1883,"base_topic":"homie","auth":false},"name":"friendlyname","ota":{"enabled":true},"device_id":"homielight"}

Trying to turn a light on via:

> $ mosquitto_pub -h localhost  -t homie/homielight/light/on/set -m "true"

 does not work.
 It does get published to the broker and i am able to read the message "true", by subscribing to topic  **homie/homielight/light/on/set**
 E.g.

> $ mosquitto_sub -h localhost -t "homie/homielight/light/on/set"
true

but nothing else happens.
 
 At least I would have expected this to result in "Light is on"/"Light is off" being logged to the serial interface?

Instead, all i get is:

>    • Wi-Fi signal quality: 76%
>   Uptime: 604s
> Triggering MQTT_PACKET_ACKNOWLEDGED event (packetId 42)...
> Triggering MQTT_PACKET_ACKNOWLEDGED event (packetId 43)...
> 〽 Sending statistics...
>   • Wi-Fi signal quality: 64%
>   Uptime: 664s
> Triggering MQTT_PACKET_ACKNOWLEDGED event (packetId 44)...
> Triggering MQTT_PACKET_ACKNOWLEDGED event (packetId 45)...

Any ideas?

**Comment by marvinroger** [comment]
The base topic must have a leading `/`. I'll add a note in the docs.

**Comment by 466** [comment]
Thanks for your quick response!

> The base topic must have a leading `/`. I'll add a note in the docs.

Leading?
For me it did only work, if the topic was followed by a '/', **using the UI bundle** for configuration.
e.g. 'homietest/'

Anyway, the wrong topic definitely was the problem :)

**Comment by marvinroger** [comment]
Oh, my english is still not as good as it could be! Glad it fixed your
issue. 😊
