### ISSUE TITLE
Examples in Dev Branch

### ISSUE THREAD

**Issue by mikecay** [marvinroger/homie#15]
Hi,

I downloaded the most dev branch and tried the LightOnOff sketch but it does not compile without making some changes to it.  In the end the following sketch is what worked.

`#include <Homie.h>

const int PIN_RELAY = 5;

HomieNode lightNode("light", "switch");

bool lightOnHandler(HomieRange range, String value) {
  if (value != "true" && value != "false") return false;

  bool on = (value == "true");
  digitalWrite(PIN_RELAY, on ? HIGH : LOW);
  lightNode.setProperty("on").send(value);
  Serial << "Light is " << (on ? "on" : "off") << endl;

  return true;
}

void setup() {
  Serial.begin(115200);
  Serial << endl << endl;
  pinMode(PIN_RELAY, OUTPUT);
  digitalWrite(PIN_RELAY, LOW);

  Homie_setFirmware("awesome-relay", "1.0.0");

  lightNode.advertise("on").settable(lightOnHandler);

  Homie.setup();
}

void loop() {
  Homie.loop();
}`

The change I made was changing Homie.setNodeProperty(lightNode, "on").send(value) to lightNode.setProperty("on").send(value).

The issue now is when I try and send a message to the node it never gets received.

On my MQTT server, I see all the properties being received from homie/relay/*  but when I sent homie/relay/light/on/set with true nothing is received.  

Thank you,

Mike

**Comment by mikecay** [comment]
The example sketch is fine, it was not overwriting the old example when I was copy it over.  However, I am still having a problem with the topic.  I send homie/relay/light/on/set but it does not get received nor does anything get output to serial or sent from the lightOnHandler.

**Comment by mikecay** [comment]
given my node had 2 relays I decided to use the LedStrip sketch as my starting point for my node.  This is my final sketch

`#include <Homie.h>

#define FW_NAME "ac_sw_os"
#define FW_VERSION "1.0.0"

/* Magic sequence for Autodetectable Binary Upload */
const char *__FLAGGED_FW_NAME = "\xbf\x84\xe4\x13\x54" FW_NAME "\x93\x44\x6b\xa7\x75";
const char *__FLAGGED_FW_VERSION = "\x6a\x3f\x3e\x0e\xe1" FW_VERSION "\xb0\x30\x48\xd4\x1a";
/* End of magic sequence for Autodetectable Binary Upload */

const unsigned char NUMBER_OF_PLUGS = 2;
const unsigned char AC_PINS[NUMBER_OF_PLUGS] = { 12, 14 };

HomieNode plugNode("light", "switch");

bool plugHandler(const HomieRange& range, const String& value) {
  plugNode.setProperty("relay").setRange(1).send("test");
  Serial << "Range " << range.index << endl;
  if (!range.isRange) return false;  // if it's not a range

  if (range.index < 1 || range.index > NUMBER_OF_PLUGS) return false;  // if it's not a valid range

  if (value != "on" && value != "off") return false;  // if the value is not valid
  bool on = (value == "on");
  digitalWrite(AC_PINS[range.index - 1], on ? HIGH : LOW);
  plugNode.setProperty("relay").setRange(range).send(value);  // Update the state of the led
  Homie.getLogger() << "Plug " << range.index << " is " << value << endl;

  return true;
}

void loopHandler() {
//  plugNode.setProperty("relay").setRange(1).send("test");
}

void setup() {
 for (int i = 0; i < NUMBER_OF_PLUGS; i++) { 
   pinMode(AC_PINS[i], OUTPUT);
   digitalWrite(AC_PINS[i], LOW);
 }

  Serial.begin(115200);
  Serial << endl << endl;
  
  Homie_setBrand("OutsideRelay"); // before Homie.setup();
  Homie_setFirmware(FW_NAME, FW_VERSION);
  plugNode.advertiseRange("relay", 1, NUMBER_OF_PLUGS).settable(plugHandler);
  Homie.setLoopFunction(loopHandler);
  Homie.setup();
}

void loop() {
  Homie.loop();
}`

In the loopHandler, when I uncomment the setproperty command, my mosquitto server receives homie/plug/light/relay_1 with a payload of test.  The problem is, when I send homie/plug/light/relay_1/set, I get nothing in plugHandler.  is that the right topic that I should be sending to?

Thank you,

Mike

**Comment by marvinroger** [comment]
Hi,

This is the repo of the MQTT convention, not the ESP8266 framework. Anyway, your problem is related to https://github.com/marvinroger/homie-esp8266/issues/250 and it was fixed there, can you please pull the latest git? It should fix it. The bug was our fault, you're not doing anything wrong.
