### ISSUE TITLE
Node or node property

### ISSUE THREAD

**Issue by bertmelis** [marvinroger/homie#16]
Imagine a water consumption meter which is read out by an esp8266. the esp counts pulses as total consumption and calculaties the current flow.
Would you split up consumption and flow into separate nodes of would you see them as different properties of 1 node.

**Comment by kwave** [comment]
I would see them as different properties of the same node. According to the specification examples, a node is defined as a sensor, the values that can be read from the sensor are the properties.

**Comment by bertmelis** [comment]
I was a bit confused with the relation to the real life "thing". When you take the current weather for example, you have different nodes: temperature, humidity, wind...
In my example, the real life thing is the watermeter from which you can pick up several items.

But as I read between the lines of your answer, when the different items are very closely related to each other, you can see them as node properties:
weather items are very loosely related: different nodes
watermeter items are closely related: node properties
rollershutter position and slat position are not related: different nodes
....

**Comment by ThomDietrich** [comment]
I believe that is the idea.
I have automated a whole coffee machine. Everything is closely related --> One node "machine" with around 10 properties ;)
