### ISSUE TITLE
Does it scale? MQTT is NOT a database...

### ISSUE THREAD

**Issue by NicSil** [marvinroger/homie#18]
I wonder if its a good idea to use MQTT as a store of devices properties: that's not its purpose.
Retain feature purpose is not for mimicing a database. There is no magic into this: datas are stored somewhere and how it is stored can make this model not scalable.

**Comment by bertmelis** [comment]
Imho it will work just fine. MQTT is indeed not  designed  as a database but IS designed  tot scale. Tuned servers reach up tot 1000000+ () concurrent clients. The number of messages is like,  I suppose.

Homie's purpose is to aid home automation so I myself will never reach that number. And if I had a critical node, I would build in local persistence and security.

You know, most people that use Viagra don't suffer any heart disease...

Anyway, I don't know how the different brokers  store their retained messages. Do they use a DB as backend?

**Comment by marvinroger** [comment]
I understand the concern. But I am convinced this is not a problem. The "retained" concept is not meant to act as a datastore, but as a temporary buffer for when a controller connects, it can immediately have access to all device information. Then, it's up to the controller to store these discoveries in a database.

You can setup your MQTT broker to store the retained messages in memory; if the broker crashes and restarts, the devices will connect back and report all information. So there's actually no need for cold storage persistence.

And, actually, MQTT is just a protocol. Indeed, if you use mosquitto this can be a problem for a very high client count. But, [VerneMQ](https://vernemq.com/) for example is meant to scale. 😉
