### ISSUE TITLE
Data configuration across the 3 components of this system.

### ISSUE THREAD

**Issue by NigelTwo** [marvinroger/homie#2]
Hello, can you confirm how the homie data described here for the MQTT broker is configured into the homie-esp8266 and the homie-server i.e.
MQTT topic                        ESP8266 (config)      homie-server (infrastructure.yml)
devices/device ID               JSON “device_id”       devices: -id
devices/device ID/$name   JSON “name”              ?
devices/device ID/$nodes  NomieNode(id,type)    nodes: -id type
 
And regarding the "node type", is there a  prescribed list of these recognised by the homie-server e.g.  shutters, temperature, heater, light.

**Comment by marvinroger** [comment]
You're right. The `infrastructure.yml` `name` field for a node is the text you want to be shown on the UI (look at the screenshot in the first page, for the shutters node the name is set to `Volets roulants`), so there is no link between this value and MQTT topics and the ESP8266 config.

No there is none. What is currently implemented is [here](https://github.com/marvinroger/homie-server/tree/49886aee3b53900723fa89fe0309cfe0cbdab220/app/js/homie/devices), but this project is very much a WIP and nothing is documented yet. But you can implement your own components if you want, as you can see this is pretty straightforward!

**Comment by NigelTwo** [comment]
Thanks, I understand the alpha/WIP thing. I just needed to understand the data layout better.
