### ISSUE TITLE
$location property.

### ISSUE THREAD

**Issue by jayaras** [marvinroger/homie#3]
Thoughts on adding a $location device property?  This would prevent having to overload the $name field with location info and possibly make searching easier..  or does this belong 'outside' of homie?

**Comment by marvinroger** [comment]
Well, device properties are properties that are actually related to the device *itself*, not it's environment. A location depends of the environment. You will tell me that on the convention, the example for the `$name` property is `Bedroom temperature sensor`, but after consideration, this is not "idiomatic" Homie, so I'll update this to `Temperature sensor`.

So yes, I think this is the role of the controller to know and manage the location of each device.
