### ISSUE TITLE
Color datatype

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/homie#33]
We need a color datatype. It could support multiple formats (RGB, hue...)

**Comment by marvinroger** [comment]
Fixed by https://github.com/marvinroger/homie/commit/a17b8b3cdf616cb46b6a4fb7ff47e78adc639698

**Comment by hondzik** [comment]
Hello,
it would be nice to have additional predefined formats for color datatype, for example rgbw and maybe hex variants #rgb and #rgbw.
