### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by PKGeorgiev** [marvinroger/homie#43]
Hi guys,

I'm 1-2 days user of Homie and I like it very much! I faced some difficulties I want to suggest some features that would be useful to everyone:

1) homie/<device-id>/$implementation/reboot - for easy reboot
2) homie/<device-id>/$implementation/report (or register) - to force a concrete device to report its nodes/properties
3) react on broadcasted register message - to notify all devices to re-register - for easier inventory.
4) homie/<device-id>/somenode/someproperty/get - to get last value that was set. Similar to #25. This will consume more memory but it will be very useful. For example imagine a simple node in NODE-RED that is able to query property's value.
5) Include some MQTT topic/payload samples for SET properties and SET config under Convention section. For example initially it was not obvious to me that homie/<device-id>/$implementation/config/set expects a JSON formatted string. Also it is not clear that HomieSetting represents a real key/value pair under "settings" section in the setting file and can be modified via a call to homie/<device-id>/$implementation/config/set. For example in [http://marvinroger.github.io/homie-esp8266/develop/advanced-usage/custom-settings/](url) add information that "percentage" setting can be set publishing MQTT message like this:
topic: homie/<device-id>/$implementation/config/set 
payload: '{"settings":{ "percentage": 50 }}'

Retained MQTT values are not always useful (imagine MQTT broker was rebooted). I think a "controller" (like node-red) should be able to control more aspects of homie device.

In all cases - great work! 

Thanks.

**Comment by euphi** [comment]
1. may be useful, indeed.

2./3. Thats what retained messages are for. The device and node attributes are sent with retained flag as soon  as a homie device connects to the broker.  This also applies for reconnection, so restart of broker is not an issue. 

4. This can also be achieved with setting the retained flag.

5. Feel free to improve the example section and create a pull request :-)

**Comment by marvinroger** [comment]
Hi 😃 
This belongs to the homie-esp8266 repo. Please fill an issue there instead 😉
