### ISSUE TITLE
homie-python

### ISSUE THREAD

**Issue by jalmeroth** [marvinroger/homie#5]
Hi there,

is there any known implementation or example of the homie-convention in python? I would like to use certain homie-esque features like …/set command, uptime, local ip, etc. on systems that are able to run python scripts. I would also be interested in your thoughts about this idea.

Keep up the good work and thanks for all your efforts!

Best regards,
Jan

**Comment by jalmeroth** [comment]
I am not a big developer, but I tried to express my idea here: https://github.com/jalmeroth/homie-python3

**Comment by jpmens** [comment]
I like this; it makes it easy for people who use Homie to do likewise with Python. A neat idea.

**Comment by jalmeroth** [comment]
As development progresses I am open for any kind of input or design considerations.

**Comment by marvinroger** [comment]
I am not a Python developer since quite a long time, I am sorry I won't be able to help on this. However, thanks for the great initiative! Don't hesitate to add your library to the README. :smile:

**Comment by jalmeroth** [comment]
Thanks for the offer @marvinroger. :)
