### ISSUE TITLE
$signal: value / interval

### ISSUE THREAD

**Issue by jalmeroth** [marvinroger/homie#8]
Shouldn't the $signal be treated same as the $uptime in v2?

Therefore I propose:
$signal/value
$signal/interval

**Comment by marvinroger** [comment]
You are right. I did not even think about that.

**Comment by marvinroger** [comment]
Done 😃

**Comment by Nzbuu** [comment]
Is it necessary to have separate `$uptime/interval` and `$signal/interval` topics? Would it be simpler to combine them and use the same value for both `$uptime` and `$signal`?

Would probably make implementation simpler too since the once function can update both at the same time.

**Comment by marvinroger** [comment]
What would be the name of the `interval` topic?

**Comment by marvinroger** [comment]
Something like:

* `$dynamic/signal`: 100
* `$dynamic/uptime`: 3612
* `$dynamic/interval`: 60

?

**Comment by Nzbuu** [comment]
yes, although I think I prefer something like `$statistics`

**Comment by marvinroger** [comment]
These are not really statistics, IMO. Let's wait for other users inputs. 😉

**Comment by euphi** [comment]
I think it is some kind of statistics, so `$statistics` or `$stats` would be fine. 

Other proposals:
* `$health`
* `$device`

I prefer $stats.

**Comment by marvinroger** [comment]
Oh? My bad! For me, statistics are the the discipline of working with numbers, but I guess that's because I'm still a student 😅
`$stats` sounds like the right thing to do, then!

**Comment by marvinroger** [comment]
https://github.com/marvinroger/homie/commit/2e28318231707197204b3b5d6dfde0f4befae146 is it fine?

**Comment by jalmeroth** [comment]
Works for me. 👍 Thank you!
